apiVersion: v1
kind: Service
metadata:
  name: anky 
  labels:
    app: tomcat-app
spec:
  selector:
    app: tomcat-app
  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
